// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeRootFilesystemConfig } from "./NativeRootFilesystemConfig.js";
import type { PermissionsPolicy } from "./PermissionsPolicy.js";
import type { RootFilesystemConfig } from "./RootFilesystemConfig.js";
import type { VmDnsConfig } from "./VmDnsConfig.js";
import type { VmLimitsConfig } from "./VmLimitsConfig.js";
import type { VmListenPolicyConfig } from "./VmListenPolicyConfig.js";

export type CreateVmConfig = { cwd?: string, env: Record<string, string>, rootFilesystem: RootFilesystemConfig, permissions?: PermissionsPolicy, limits?: VmLimitsConfig, dns?: VmDnsConfig, nativeRoot?: NativeRootFilesystemConfig, listen?: VmListenPolicyConfig, loopbackExemptPorts: Array<number>, };
