// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsPermissionRule } from "./FsPermissionRule.js";
import type { PermissionMode } from "./PermissionMode.js";

export type FsPermissionRuleSet = { default?: PermissionMode, rules: Array<FsPermissionRule>, };
