// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternPermissionRule } from "./PatternPermissionRule.js";
import type { PermissionMode } from "./PermissionMode.js";

export type PatternPermissionRuleSet = { default?: PermissionMode, rules: Array<PatternPermissionRule>, };
