// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode.js";

export type PatternPermissionRule = { mode: PermissionMode, operations: Array<string>, patterns: Array<string>, };
