// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatternPermissionRuleSet } from "./PatternPermissionRuleSet.js";
import type { PermissionMode } from "./PermissionMode.js";

export type PatternPermissionScope = PermissionMode | PatternPermissionRuleSet;
