// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FsPermissionScope } from "./FsPermissionScope.js";
import type { PatternPermissionScope } from "./PatternPermissionScope.js";

export type PermissionsPolicy = { fs?: FsPermissionScope, network?: PatternPermissionScope, childProcess?: PatternPermissionScope, process?: PatternPermissionScope, env?: PatternPermissionScope, binding?: PatternPermissionScope, };
