// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RootFilesystemEntry } from "./RootFilesystemEntry.js";
import type { RootFilesystemLowerDescriptor } from "./RootFilesystemLowerDescriptor.js";
import type { RootFilesystemMode } from "./RootFilesystemMode.js";

export type RootFilesystemConfig = { mode: RootFilesystemMode, disableDefaultBaseLayer: boolean, lowers: Array<RootFilesystemLowerDescriptor>, bootstrapEntries: Array<RootFilesystemEntry>, };
