// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RootFilesystemEntry } from "./RootFilesystemEntry.js";

export type RootFilesystemLowerDescriptor = { "kind": "snapshot", entries: Array<RootFilesystemEntry>, } | { "kind": "bundledBaseFilesystem" };
