// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VmDnsConfig = { nameServers: Array<string>, overrides: { [key in string]?: Array<string> }, };
