// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpLimitsConfig } from "./AcpLimitsConfig.js";
import type { HttpLimitsConfig } from "./HttpLimitsConfig.js";
import type { JsRuntimeLimitsConfig } from "./JsRuntimeLimitsConfig.js";
import type { PluginLimitsConfig } from "./PluginLimitsConfig.js";
import type { PythonLimitsConfig } from "./PythonLimitsConfig.js";
import type { ResourceLimitsConfig } from "./ResourceLimitsConfig.js";
import type { ToolLimitsConfig } from "./ToolLimitsConfig.js";
import type { WasmLimitsConfig } from "./WasmLimitsConfig.js";

export type VmLimitsConfig = { resources?: ResourceLimitsConfig, http?: HttpLimitsConfig, tools?: ToolLimitsConfig, plugins?: PluginLimitsConfig, acp?: AcpLimitsConfig, jsRuntime?: JsRuntimeLimitsConfig, python?: PythonLimitsConfig, wasm?: WasmLimitsConfig, };
