use codex_otel::metrics::names::{
    API_CALL_COUNT_METRIC, API_CALL_DURATION_METRIC, PROFILE_USAGE_METRIC,
    RESPONSES_API_ENGINE_IAPI_TBT_DURATION_METRIC, RESPONSES_API_ENGINE_IAPI_TTFT_DURATION_METRIC,
    RESPONSES_API_ENGINE_SERVICE_TBT_DURATION_METRIC,
    RESPONSES_API_ENGINE_SERVICE_TTFT_DURATION_METRIC,
    RESPONSES_API_INFERENCE_TIME_DURATION_METRIC, RESPONSES_API_OVERHEAD_DURATION_METRIC,
    SSE_EVENT_COUNT_METRIC, SSE_EVENT_DURATION_METRIC, STARTUP_PREWARM_AGE_AT_FIRST_TURN_METRIC,
    STARTUP_PREWARM_DURATION_METRIC, THREAD_STARTED_METRIC, TOOL_CALL_COUNT_METRIC,
    TOOL_CALL_DURATION_METRIC, TURN_E2E_DURATION_METRIC, TURN_NETWORK_PROXY_METRIC,
    TURN_TOKEN_USAGE_METRIC, TURN_TOOL_CALL_METRIC, TURN_TTFM_DURATION_METRIC,
    TURN_TTFT_DURATION_METRIC, WEBSOCKET_EVENT_COUNT_METRIC, WEBSOCKET_EVENT_DURATION_METRIC,
    WEBSOCKET_REQUEST_COUNT_METRIC, WEBSOCKET_REQUEST_DURATION_METRIC,
};

const METRIC_NAMES: &[&str] = &[
    TOOL_CALL_COUNT_METRIC,
    TOOL_CALL_DURATION_METRIC,
    API_CALL_COUNT_METRIC,
    API_CALL_DURATION_METRIC,
    SSE_EVENT_COUNT_METRIC,
    SSE_EVENT_DURATION_METRIC,
    WEBSOCKET_REQUEST_COUNT_METRIC,
    WEBSOCKET_REQUEST_DURATION_METRIC,
    WEBSOCKET_EVENT_COUNT_METRIC,
    WEBSOCKET_EVENT_DURATION_METRIC,
    RESPONSES_API_OVERHEAD_DURATION_METRIC,
    RESPONSES_API_INFERENCE_TIME_DURATION_METRIC,
    RESPONSES_API_ENGINE_IAPI_TTFT_DURATION_METRIC,
    RESPONSES_API_ENGINE_SERVICE_TTFT_DURATION_METRIC,
    RESPONSES_API_ENGINE_IAPI_TBT_DURATION_METRIC,
    RESPONSES_API_ENGINE_SERVICE_TBT_DURATION_METRIC,
    TURN_E2E_DURATION_METRIC,
    TURN_TTFT_DURATION_METRIC,
    TURN_TTFM_DURATION_METRIC,
    TURN_NETWORK_PROXY_METRIC,
    TURN_TOOL_CALL_METRIC,
    TURN_TOKEN_USAGE_METRIC,
    PROFILE_USAGE_METRIC,
    STARTUP_PREWARM_DURATION_METRIC,
    STARTUP_PREWARM_AGE_AT_FIRST_TURN_METRIC,
    THREAD_STARTED_METRIC,
];

#[test]
fn metric_names_are_static_codex_names() {
    for name in METRIC_NAMES {
        assert!(name.starts_with("codex."), "{name}");
        assert!(
            name.bytes().all(|byte| byte.is_ascii_lowercase()
                || byte.is_ascii_digit()
                || b"._".contains(&byte)),
            "{name}"
        );

        for forbidden in ["secret", "password", "authorization", "api_key", "bearer"] {
            assert!(!name.contains(forbidden), "{name}");
        }
    }
}
