#!/usr/bin/env zx
// CI entry point (zx). Run with: `npx zx scripts/ci.mjs <phase>` (or `pnpm dlx zx`).
//
// Phases (disjoint so .github/workflows/ci.yml can run them on parallel runners):
//   all             (default) full serial run — local use
//   js-checks       install, build, generated/type/boundary checks, publish tests
//   rust-lint       cargo fmt + clippy
//   rust-test       guest WASM commands + full cargo workspace tests (nextest)
//   js-test         turbo test suites against a pinned sidecar (no network e2e)
//   nightly-extras  network-e2e turbo tests + timing + #[ignore]d expensive tests
//
// zx injects the $, cd, echo, fs, path, argv, os globals — no imports needed.

$.verbose = true; // stream each command's output live

const ROOT = path.resolve(__dirname, "..");
cd(ROOT);

// Self-hosted-runner layout (a pinned toolchain under /workspace) — mirror the
// old bash bootstrap so those runners resolve cargo/rustc correctly.
const selfHostedToolchain =
  "/workspace/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin";
if (fs.existsSync("/workspace/.cargo") && fs.existsSync(selfHostedToolchain)) {
  process.env.CARGO_HOME = "/workspace/.cargo";
  process.env.RUSTUP_HOME = "/workspace/.rustup";
  process.env.PATH = `/workspace/.cargo/bin:${process.env.PATH}`;
  process.env.RUSTC = `${selfHostedToolchain}/rustc`;
  process.env.RUSTDOC = `${selfHostedToolchain}/rustdoc`;
}
process.env.CARGO_HTTP_TIMEOUT ??= "120";
process.env.CARGO_NET_RETRY ??= "10";

// Run a labeled step inside a foldable GitHub Actions log group.
async function step(label, cmd) {
  echo(`::group::==> ${label}`);
  try {
    await cmd();
  } finally {
    echo("::endgroup::");
  }
}

// $ with extra environment for a single command (like bash `env VAR=val cmd`).
function withEnv(extra) {
  return $({ env: { ...process.env, ...extra } });
}

// The service fs/shell regression tests stage guest WASM command binaries and
// fail hard when missing. In CI these arrive prebuilt via the wasm-commands
// artifact; skip the ~12-minute build when they are already present.
async function buildWasmCommands() {
  const dir = path.join(ROOT, "packages/core/commands");
  if (fs.existsSync(dir) && fs.readdirSync(dir).length > 0) {
    echo("==> guest WASM commands already present; skipping build");
    return;
  }
  await step("make -C registry/native wasm", () => $`make -C registry/native wasm`);
  await step("copy-wasm-commands", () => $`node packages/core/scripts/copy-wasm-commands.mjs`);
}

// Pin the sidecar binary for the JS test suites. Without this the first vitest
// file that needs a sidecar sees the v8-bridge asset regenerated by the turbo
// ^build tasks (mtime newer than the binary) and runs `cargo build` INSIDE its
// own 120s test timeout — the deterministic-timeout footgun we chased earlier.
async function pinSidecar() {
  await step("cargo build -p secure-exec-sidecar", () => $`cargo build -p secure-exec-sidecar`);
  process.env.SECURE_EXEC_SIDECAR_BIN = path.join(
    ROOT,
    "target/debug/secure-exec-sidecar",
  );
}

async function jsChecks() {
  await step("pnpm install", () => $`pnpm install --frozen-lockfile`);
  await step("pnpm build", () => $`pnpm build`);
  await step("check-generated", () => $`pnpm run check-generated`);
  await step("check-types", () => $`pnpm check-types`);
  await step("boundary check test", () => $`node --test scripts/check-secure-exec-boundary.test.mjs`);
  await step("boundary check", () => $`node scripts/check-secure-exec-boundary.mjs`);
  await step("no-escaping-deps test", () => $`node --test scripts/check-no-escaping-local-deps.test.mjs`);
  await step("no-escaping-deps check", () => $`node scripts/check-no-escaping-local-deps.mjs`);
  await step("publish check-types", () => $`pnpm --dir scripts/publish run check-types`);
  await step("publish tests", () => $`pnpm --dir scripts/publish test`);
}

async function rustLint() {
  await step("cargo fmt --check", () => $`cargo fmt --check`);
  await step("cargo clippy", () => $`cargo clippy --workspace --all-targets -- -D warnings`);
}

async function rustTest() {
  await buildWasmCommands();
  // cargo-nextest runs one process per test, isolating the process-global
  // V8/Pyodide platform + caches that previously forced --test-threads=1.
  // Timing-sensitive tests are skipped by default. Doctests are not run by
  // nextest, so run them separately.
  const profile = process.env.NEXTEST_PROFILE || "default";
  await step(`cargo nextest run (${profile})`, () =>
    withEnv({ CARGO_INCREMENTAL: "0" })`cargo nextest run --workspace --profile ${profile}`,
  );
  await step("cargo test --doc", () =>
    withEnv({ CARGO_INCREMENTAL: "0" })`cargo test --workspace --doc`,
  );
}

async function jsTest() {
  await step("pnpm install", () => $`pnpm install --frozen-lockfile`);
  await step("pnpm build", () => $`pnpm build`);
  await buildWasmCommands();
  await pinSidecar();
  // Network e2e coverage runs in the nightly job, keeping the PR path hermetic.
  await step("turbo test", () => $`pnpm exec turbo run test --concurrency=1`);
}

async function nightlyExtras() {
  await step("pnpm install", () => $`pnpm install --frozen-lockfile`);
  await step("pnpm build", () => $`pnpm build`);
  await buildWasmCommands();
  await pinSidecar();
  await step("turbo test (network e2e)", () =>
    withEnv({ SECURE_EXEC_E2E_NETWORK: "1" })`pnpm exec turbo run test --concurrency=1 --force`,
  );
  // Timing-sensitive tests are gated off the default suite (they flake under
  // parallel CPU contention); run them here on a quiet, serial lane.
  await step("cargo nextest (timing lane)", () =>
    withEnv({ CARGO_INCREMENTAL: "0", SECURE_EXEC_RUN_TIMING_TESTS: "1" })`cargo nextest run --workspace --profile timing --run-ignored all`,
  );
  // Expensive resource-saturation tests are #[ignore]d in the default suite;
  // the nightly is where they actually run.
  await step("cargo test --ignored", () =>
    withEnv({ CARGO_INCREMENTAL: "0" })`cargo test --workspace -- --ignored --test-threads=1`,
  );
}

const phase = argv._[0] ?? "all";
switch (phase) {
  case "js-checks":
    await jsChecks();
    break;
  case "rust-lint":
    await rustLint();
    break;
  case "rust-test":
    await rustTest();
    break;
  case "js-test":
    await jsTest();
    break;
  case "nightly-extras":
    await nightlyExtras();
    break;
  case "all":
    await jsChecks();
    await rustLint();
    await rustTest();
    await pinSidecar();
    if (process.env.CI_FORK_PULL_REQUEST === "1") {
      await step("turbo test", () => $`pnpm exec turbo run test --concurrency=1`);
    } else {
      await step("turbo test (network e2e)", () =>
        withEnv({ SECURE_EXEC_E2E_NETWORK: "1" })`pnpm exec turbo run test --concurrency=1`,
      );
    }
    break;
  default:
    echo(`unknown ci phase: ${phase}`);
    process.exit(1);
}
