#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ -d /workspace/.cargo && -d /workspace/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin ]]; then
	export CARGO_HOME=/workspace/.cargo
	export RUSTUP_HOME=/workspace/.rustup
	export PATH="/workspace/.cargo/bin:${PATH}"
	export RUSTC=/workspace/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc
	export RUSTDOC=/workspace/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustdoc
fi

export CARGO_HTTP_TIMEOUT="${CARGO_HTTP_TIMEOUT:-120}"
export CARGO_NET_RETRY="${CARGO_NET_RETRY:-10}"

run_step() {
	echo ""
	echo "==> $*"
	"$@"
}

run_step pnpm install --frozen-lockfile
run_step pnpm build
run_step pnpm run check-generated
run_step pnpm check-types
run_step node --test scripts/check-secure-exec-boundary.test.mjs
run_step node scripts/check-secure-exec-boundary.mjs
run_step node --test scripts/check-no-escaping-local-deps.test.mjs
run_step node scripts/check-no-escaping-local-deps.mjs
run_step pnpm --dir scripts/publish run check-types
run_step pnpm --dir scripts/publish test
run_step cargo fmt --check
run_step cargo clippy --workspace --all-targets -- -D warnings
# Service fs/shell regression tests stage guest WASM command binaries
# (registry/native or packages/core/commands) and fail hard when missing.
run_step make -C registry/native wasm
run_step node packages/core/scripts/copy-wasm-commands.mjs
run_step env CARGO_INCREMENTAL=0 cargo test --workspace -- --test-threads=1

# Pin the sidecar binary for the JS test suites. Without this, the first
# vitest file that needs a sidecar sees the v8-bridge asset regenerated by
# the turbo ^build tasks (an mtime newer than the binary) and runs
# `cargo build -p secure-exec-sidecar` INSIDE its own 120s test timeout —
# a multi-minute rebuild on CI runners (and N concurrent cargo builds under
# file parallelism), which presented as deterministic test timeouts.
run_step cargo build -p secure-exec-sidecar
export SECURE_EXEC_SIDECAR_BIN="$ROOT_DIR/target/debug/secure-exec-sidecar"

if [[ "${CI_FORK_PULL_REQUEST:-0}" == "1" ]]; then
	run_step pnpm exec turbo run test --concurrency=1
else
	run_step env SECURE_EXEC_E2E_NETWORK=1 pnpm exec turbo run test --concurrency=1
fi
